// <auto-generated />
using System;
using EFRandevouDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFRandevouDAL.Migrations
{
    [DbContext(typeof(RandevouDbContext))]
    [Migration("20181028075517_InitialValues")]
    partial class InitialValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RandevouData.Messages.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("MessageContent")
                        .IsRequired();

                    b.Property<DateTime?>("ReadDate");

                    b.Property<DateTime>("SendDate");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RandevouData.Users.Details.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("Heigth");

                    b.Property<string>("Region");

                    b.Property<int>("Tattos");

                    b.Property<int>("UserId");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersDetails");
                });

            modelBuilder.Entity("RandevouData.Users.Details.UserDetailsDictionaryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DetailsType")
                        .IsRequired();

                    b.Property<string>("DisplayName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ObjectType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UserDetailsDictionary");

                    b.HasData(
                        new { Id = 1, DetailsType = "EyesColor", DisplayName = "Brązowe", IsDeleted = false, Name = "Brązowe", ObjectType = "boolean" },
                        new { Id = 2, DetailsType = "EyesColor", DisplayName = "Niebieskie", IsDeleted = false, Name = "Niebieskie", ObjectType = "boolean" },
                        new { Id = 3, DetailsType = "EyesColor", DisplayName = "zielone", IsDeleted = false, Name = "zielone", ObjectType = "boolean" },
                        new { Id = 4, DetailsType = "HairColor", DisplayName = "ciemne", IsDeleted = false, Name = "ciemne", ObjectType = "boolean" },
                        new { Id = 5, DetailsType = "HairColor", DisplayName = "jasne", IsDeleted = false, Name = "jasne", ObjectType = "boolean" },
                        new { Id = 6, DetailsType = "Interests", DisplayName = "piłka nożna", IsDeleted = false, Name = "football", ObjectType = "boolean" },
                        new { Id = 7, DetailsType = "Interests", DisplayName = "koszykówka", IsDeleted = false, Name = "koszykówka", ObjectType = "boolean" },
                        new { Id = 8, DetailsType = "Interests", DisplayName = "szachy", IsDeleted = false, Name = "szachy", ObjectType = "boolean" }
                    );
                });

            modelBuilder.Entity("RandevouData.Users.Details.UsersDetailsItemsValues", b =>
                {
                    b.Property<int>("UserDetailsId");

                    b.Property<int>("UserDetailsDictionaryItemId");

                    b.Property<bool>("Value");

                    b.HasKey("UserDetailsId", "UserDetailsDictionaryItemId");

                    b.HasAlternateKey("UserDetailsDictionaryItemId", "UserDetailsId");

                    b.ToTable("UsersDetailsItemsValues");
                });

            modelBuilder.Entity("RandevouData.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("DisplayName");

                    b.Property<char>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RandevouData.Users.Details.UserDetails", b =>
                {
                    b.HasOne("RandevouData.Users.User", "User")
                        .WithOne("UserDetails")
                        .HasForeignKey("RandevouData.Users.Details.UserDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RandevouData.Users.Details.UsersDetailsItemsValues", b =>
                {
                    b.HasOne("RandevouData.Users.Details.UserDetailsDictionaryItem")
                        .WithMany("DetailsItemsValues")
                        .HasForeignKey("UserDetailsDictionaryItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RandevouData.Users.Details.UserDetails")
                        .WithMany("DetailsItemsValues")
                        .HasForeignKey("UserDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
