// <auto-generated />
using System;
using EFRandevouDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFRandevouDAL.Migrations
{
    [DbContext(typeof(RandevouDbContext))]
    [Migration("20181016164353_UserDictionaryItems2")]
    partial class UserDictionaryItems2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RandevouData.Messages.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FromUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("MessageContent")
                        .IsRequired();

                    b.Property<DateTime?>("ReadDate");

                    b.Property<DateTime>("SendDate");

                    b.Property<int>("ToUserId");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RandevouData.Users.Details.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("Heigth");

                    b.Property<string>("Region");

                    b.Property<int>("Tattos");

                    b.Property<int>("UserId");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersDetails");
                });

            modelBuilder.Entity("RandevouData.Users.Details.UserDetailsDictionaryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DetailsType")
                        .IsRequired();

                    b.Property<string>("DisplayName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ObjectType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UserDetailsDictionary");
                });

            modelBuilder.Entity("RandevouData.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("DisplayName");

                    b.Property<char>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RandevouData.Messages.Message", b =>
                {
                    b.HasOne("RandevouData.Users.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RandevouData.Users.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RandevouData.Users.Details.UserDetails", b =>
                {
                    b.HasOne("RandevouData.Users.User", "User")
                        .WithOne("UserDetails")
                        .HasForeignKey("RandevouData.Users.Details.UserDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
